#  EDUNET FOUNDATION - Self Practice Excercise

## Lab 1
## Problem Statement

### ""For extended data of CO2 emission ("Excercise_Data_1.csv"). 
### Company needs a multiple regression model to predict the emission generate from a newly produced car.

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv("FuelConsumption.csv")
df

,Year,MAKE,MODEL,VEHICLE CLASS,ENGINE SIZE,CYLINDERS,TRANSMISSION,FUEL,FUEL CONSUMPTION,COEMISSIONS
0,2000,ACURA,1.6EL,COMPACT,1.6,4,A4,X,10.5,216
1,2000,ACURA,1.6EL,COMPACT,1.6,4,M5,X,9.8,205
2,2000,ACURA,3.2TL,MID-SIZE,3.2,6,AS5,Z,13.7,265
3,2000,ACURA,3.5RL,MID-SIZE,3.5,6,A4,Z,15.0,301
4,2000,ACURA,INTEGRA,SUBCOMPACT,1.8,4,A4,X,11.4,230
...,...,...,...,...,...,...,...,...,...,...
634,2000,VOLVO,V70 AWD TURBO,STATION WAGON - MID-SIZE,2.4,5,A4,Z,14.4,288
635,2000,VOLVO,V70 GLT TURBO,STATION WAGON - MID-SIZE,2.4,5,A4,Z,13.6,274
636,2000,VOLVO,V70 T5 TURBO,STATION WAGON - MID-SIZE,2.3,5,A4,Z,13.9,274
637,2000,VOLVO,V70 T5 TURBO,STATION WAGON - MID-SIZE,2.3,5,M5,Z,13.0,260
638,2000,VOLVO,V70R AWD TURBO,STATION WAGON - MID-SIZE,2.4,5,A5,Z,14.7,299

In [3]:
print(df.info())
print("\n")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639 entries, 0 to 638
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              639 non-null    int64
 1   MAKE              639 non-null    object
 2   MODEL             639 non-null    object
 3   VEHICLE CLASS     639 non-null    object
 4   ENGINE SIZE       639 non-null    float64
 5   CYLINDERS         639 non-null    int64
 6   TRANSMISSION      639 non-null    object
 7   FUEL              639 non-null    object
 8   FUEL CONSUMPTION  639 non-null    float64
 9   COEMISSIONS       639 non-null    int64
dtypes: float64(2), int64(3), object(5)
memory usage: 50.1+ KB
None


         Year  ENGINE SIZE   CYLINDERS  FUEL CONSUMPTION  COEMISSIONS
count   639.0   639.000000  639.000000        639.000000    639.000000
mean   2000.0     3.265728    5.805947         14.713615    296.809077
std       0.0     1.231012    1.625588          3.307044     65.504178
min    2000.0     1.000000    3.000000          4.900000    104.000000
25%    2000.0     2.200000    4.000000         12.500000    253.000000
50%    2000.0     3.000000    6.000000         14.400000    288.000000
75%    2000.0     4.300000    6.000000         16.600000    343.000000
max    2000.0     8.000000   12.000000         30.200000    582.000000

In [5]:
cols = df.columns

In [ ]:
cols.head